### ISSUE TITLE
Missing libSceVshBridge_stub

### ISSUE THREAD

**Issue by Voxel9** [xyzz/vita-idu#2]
Hello,

I cannot seem to contact you privately, so I thought I may open a quick issue here.
My compiler seems to be missing libSceVshBridge_stub.a, which looks as if is needed to compile the source.

My question is where may I find this file? Is it bundled in the newer, latest nightly SDK builds, or is there a specific place I need to go to compile/download it?

Any help retrieving this file would be greatly appreciated, as this library looks as if it holds some useful functions. :)

-Voxel

**Comment by xyzz** [comment]
It's in the latest SDK https://goo.gl/QpX5zM

**Comment by Voxel9** [comment]
Thank you. I had a bit of a hunch that it would be.
